In [3]:
import pandas as pd

In [4]:
url="https://raw.githubusercontent.com/josevalladares99/etl-data-pipeline/refs/heads/main/data/raw/polizas.csv"

In [5]:
df=pd.read_csv(url)
df.head()

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaN,184,42,15,2,"829,53",NaN,139253.11
1,2,2026/02/16,2408,35,11,12,NaN,"12,22","27.544,32"
2,3,02-14-25,540,42,4,9,1611.53,"92,05","173,298.36"
3,4,09-01-2026,2821,40,10,5,1866.62,456.99,244461.27
4,5,2026-02-13,945,23,9,11,-,"324,08",123407.75

In [6]:
df.shape
df.columns

Index(['id_poliza', 'fecha_emision', 'id_cliente', 'id_corredor',
       'id_aseguradora', 'id_tipo_seguro', 'prima', 'comision',
       'monto_asegurado'],
      dtype='object')

In [7]:
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    22739 non-null  object
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            21840 non-null  object
 7   comision         21715 non-null  object
 8   monto_asegurado  21787 non-null  object
dtypes: int64(5), object(4)
memory usage: 1.7+ MB

id_poliza             0
fecha_emision      2411
id_cliente            0
id_corredor           0
id_aseguradora        0
id_tipo_seguro        0
prima              3310
comision           3435
monto_asegurado    3363
dtype: int64

Limpieza de datos

In [20]:
polizas=df.copy()


polizas = polizas.replace(
    ["N/A", "-", "", " "],
    np.nan
)

In [21]:

polizas.columns = (
    polizas.columns
        .str.lower()
        .str.strip()
        .str.replace(" ", "_")
)

polizas.columns

Index(['id_poliza', 'fecha_emision', 'id_cliente', 'id_corredor',
       'id_aseguradora', 'id_tipo_seguro', 'prima', 'comision',
       'monto_asegurado'],
      dtype='object')

In [23]:

cols_numericas = ["prima", "comision", "monto_asegurado"]

for col in cols_numericas:
    polizas[col] = (
        polizas[col]
            .astype(str)
            .str.replace(".", "", regex=False)   # elimina miles
            .str.replace(",", ".", regex=False)  # coma → decimal
    )

    polizas[col] = pd.to_numeric(polizas[col], errors="coerce")

In [24]:

polizas["fecha_emision"] = pd.to_datetime(
    polizas["fecha_emision"],
    errors="coerce",
    dayfirst=True
)

/tmp/ipykernel_1059/1783248925.py:1: UserWarning: Parsing dates in %Y/%m/%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  polizas["fecha_emision"] = pd.to_datetime(

In [25]:
polizas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25150 entries, 0 to 25149
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id_poliza        25150 non-null  int64
 1   fecha_emision    4522 non-null   datetime64[ns]
 2   id_cliente       25150 non-null  int64
 3   id_corredor      25150 non-null  int64
 4   id_aseguradora   25150 non-null  int64
 5   id_tipo_seguro   25150 non-null  int64
 6   prima            20150 non-null  float64
 7   comision         20008 non-null  float64
 8   monto_asegurado  20179 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(5)
memory usage: 1.7 MB

In [26]:
polizas.isna().sum().sort_values(ascending=False)

fecha_emision      20628
comision            5142
prima               5000
monto_asegurado     4971
id_poliza              0
id_aseguradora         0
id_corredor            0
id_cliente             0
id_tipo_seguro         0
dtype: int64

Separar valores validos y rechazados

In [27]:

campos_clave = [
    "fecha_emision",
    "id_cliente",
    "prima",
    "monto_asegurado"
]
polizas_validas = polizas.dropna(subset=campos_clave)

polizas_nulas = polizas[
    polizas[campos_clave].isna().any(axis=1)
]

In [30]:
print("Polizas válidas:", polizas_validas.shape)
print("Polizas con nulos:", polizas_nulas.shape)

Polizas válidas: (2922, 9)
Polizas con nulos: (22228, 9)

Exportar datos

In [31]:

polizas_validas.to_csv("polizas_curated.csv", index=False)
polizas_nulas.to_csv("polizas_rejects.csv", index=False)

In [32]:
!pip install sqlalchemy psycopg2-binary

from sqlalchemy import create_engine
import pandas as pd

database_url = "postgresql://etl_user:oBPWTDnwlDkov4SzFc8zpJwu1kTOiolN@dpg-d6qu7s450q8c73bpf590-a.oregon-postgres.render.com/etl_seguros_k3sp"

engine = create_engine(database_url)

test = pd.read_sql("SELECT 1", engine)

print(test)

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.48)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 35.3 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.11
   ?column?
0         1

In [33]:
polizas_validas.to_sql("polizas_curated", con=engine, if_exists="replace", index=False)
polizas_nulas.to_sql("polizas_rejects", con=engine, if_exists="replace", index=False)

228

In [34]:
pd.read_sql(
"SELECT * FROM polizas_curated LIMIT 10",
engine
)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,10,2026-01-24,2281,69,13,3,79138.00000,67.44,2.071000e+06
1,26,2025-07-29,2295,71,11,4,61446.00000,149.78,3.667097e+06
2,45,2025-12-11,2278,66,3,11,153937.00000,24041.00,1.147323e+02
3,49,2025-08-11,1122,2,14,4,33732.00000,6959.00,4.721014e+06
4,50,2025-02-22,717,49,15,10,51878.00000,86.45,6.687199e+04
5,66,2025-03-04,1352,21,12,6,77633.00000,14721.00,1.128291e+07
6,74,2025-01-04,2814,64,5,7,1.80988,35853.00,2.797825e+07
7,82,2025-07-18,2392,21,3,4,0.00000,8363.00,3.386699e+01
8,99,2025-05-12,490,57,1,1,71612.00000,15979.00,2.392967e+06
9,104,2025-10-20,3524,7,11,8,14944.00000,1064.00,1.792505e+01

In [35]:
pd.read_sql(
"SELECT * FROM polizas_rejects LIMIT 10",
engine
)

,id_poliza,fecha_emision,id_cliente,id_corredor,id_aseguradora,id_tipo_seguro,prima,comision,monto_asegurado
0,1,NaT,184,42,15,2,829.53,NaN,1.392531e+07
1,2,2026-02-16,2408,35,11,12,NaN,12.22,2.754432e+04
2,3,NaT,540,42,4,9,161153.00,92.05,1.732984e+02
3,4,NaT,2821,40,10,5,186662.00,45699.00,2.444613e+07
4,5,NaT,945,23,9,11,NaN,324.08,1.234078e+07
5,6,NaT,1295,17,1,1,94349.00,NaN,7.196843e+06
6,7,NaT,1254,25,11,4,140082.00,18840.00,2.582029e+07
7,8,NaT,887,77,3,8,167056.00,25875.00,NaN
8,9,NaT,1670,66,8,12,NaN,131.85,1.258048e+07
9,11,NaT,2590,25,8,4,NaN,NaN,NaN

In [36]:
from google.colab import files
files.download("polizas_curated.csv")
files.download("polizas_rejects.csv")