In [ ]:
import pandas as pd
import numpy as np

In [ ]:
url="https://raw.githubusercontent.com/josevalladares99/etl-data-pipeline/refs/heads/main/data/raw/aseguradoras.csv"

In [ ]:
df=pd.read_csv(url)
df.head()

   id_aseguradora         nombre         pais rating_riesgo
0               1  Aseguradora 1   Costa Rica          Alto
1               2  Aseguradora 2  El Salvador          Bajo
2               3  Aseguradora 3  El Salvador           NaN
3               4  Aseguradora 4   Costa Rica         Medio
4               5  Aseguradora 5   ElSalvador             B

Exploración de datos

In [ ]:
df.shape

(15, 4)

In [ ]:
df.columns

Index(['id_aseguradora', 'nombre', 'pais', 'rating_riesgo'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_aseguradora  15 non-null     int64
 1   nombre          15 non-null     object
 2   pais            13 non-null     object
 3   rating_riesgo   12 non-null     object
dtypes: int64(1), object(3)
memory usage: 612.0+ bytes

In [ ]:
df.isnull().sum()

id_aseguradora    0
nombre            0
pais              2
rating_riesgo     3
dtype: int64

Limpieza de datos

In [ ]:
aseguradoras=df.copy

In [ ]:
df['rating_riesgo']=df['rating_riesgo'].str.upper()

In [ ]:
df['pais']=df['pais'].replace('ElSalvador','El Salvador')

In [ ]:
print(df['pais'].unique())

['Costa Rica' 'El Salvador' nan 'Guatemala' 'Panamá' 'Honduras']

In [ ]:
df['pais']=df['pais'].str.strip()

In [ ]:
df['pais']=df['pais'].replace(to_replace='ElSalvador',value='El Salvador')

In [ ]:
print(df['pais'].unique())

['Costa Rica' 'El Salvador' nan 'Guatemala' 'Panamá' 'Honduras']

In [ ]:
print(df['rating_riesgo'].unique())

['ALTO' 'BAJO' nan 'MEDIO' 'B' 'D']

In [ ]:
aseguradoras = df.copy()

Separación datos validos y rechazados